version: "3.8"

services:
  php:
    # container_name: php-8-3
    build:
      context: ./docker/php_8_3_nginx
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/project
      - ./config/php:/usr/local/etc/php/conf.d
    working_dir: /var/www/project
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - php-container-net
    command: >
      sh -c "composer install --no-interaction && php-fpm"

  nginx:
    # container_name: nginx
    image: nginx:latest
    volumes:
      - ./public:/var/www/project
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
      - mysql
    networks:
      - php-container-net

  mysql:
    # container_name: mysql-8-4
    image: mysql:8.4
    ports:
      - 3306:3306
    volumes:
      - ./databases/mysql-8-4:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - php-container-net

networks:
  php-container-net:
    name: php-container-net
